// This file has been modified by Chris Zimmerman.
// This file, along with the other original AntiTheft application code
// can be found at tinyos.net 

/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../Nodes/antitheft.h.
 */

public class Constants  {
    public static final byte LOW_BATTERY = 1;
    public static final byte DIS_SETTINGS = 42;
    public static final short DEFAULT_CHECK_INTERVAL = 1000;
    public static final byte BROADCAST = 4;
    public static final byte DEFAULT_DETECT = 1;
    public static final byte AM_THEFT = 99;
    public static final byte AM_SETTINGS = 54;
    public static final byte COL_ALERTS = 11;
    public static final byte DEFAULT_ALERT = 4;
    public static final byte AM_ALERT = 22;
}
